export const PERMISSION_ACTIONS = {
  CREATE: 'CREATE_PERMISSION',
  UPDATE: 'UPDATE_PERMISSION',
  ARCHIVE: 'ARCHIVE_PERMISSION',
  RESTORE: 'RESTORE_PERMISSION',
  PAGINATED_LIST: 'PAGINATED_LIST_PERMISSION',
  BY_NAME: 'BY_NAME_PERMISSION',
  BY_RESOURCE_ACTION: 'BY_RESOURCE_ACTION_PERMISSION',
  COMBOBOX: 'COMBOBOX_PERMISSION',
} as const;
