export const ROLE_ACTIONS = {
  CREATE: 'CREATE_ROLE',
  CREATE_WITH_PERMISSIONS: 'CREATE_ROLE_WITH_PERMISSIONS',
  UPDATE: 'UPDATE_ROLE',
  ARCHIVE: 'ARCHIVE_ROLE',
  RESTORE: 'RESTORE_ROLE',
  PAGINATED_LIST: 'PAGINATED_LIST_ROLE',
  BY_NAME: 'BY_NAME_ROLE',
  COMBOBOX: 'COMBOBOX_ROLE',
  ASSIGN_PERMISSIONS: 'ASSIGN_PERMISSIONS_TO_ROLE',
  REMOVE_PERMISSIONS: 'REMOVE_PERMISSIONS_FROM_ROLE',
} as const;
