export const ROLE_ACTIONS = {
  CREATE: 'CREATE_ROLE',
  UPDATE: 'UPDATE_ROLE',
  ARCHIVE: 'ARCHIVE_ROLE',
  RESTORE: 'RESTORE_ROLE',
  PAGINATED_LIST: 'PAGINATED_LIST_ROLE',
  BY_NAME: 'BY_NAME_ROLE',
  COMBOBOX: 'COMBOBOX_ROLE',
} as const;
