export const USER_PERMISSION_ACTIONS = {
  CREATE: 'CREATE_USER_PERMISSION',
  ASSIGN_TO_USER: 'ASSIGN_PERMISSIONS_TO_USER',
  REMOVE_FROM_USER: 'REMOVE_PERMISSIONS_FROM_USER',
  DENY_TO_USER: 'DENY_PERMISSIONS_TO_USER',
  GRANT_TO_USER: 'GRANT_PERMISSIONS_TO_USER',
  FIND_BY_USER_ID: 'FIND_USER_PERMISSIONS_BY_USER_ID',
  FIND_ALLOWED_BY_USER_ID: 'FIND_ALLOWED_PERMISSIONS_BY_USER_ID',
  FIND_DENIED_BY_USER_ID: 'FIND_DENIED_PERMISSIONS_BY_USER_ID',
  EXISTS: 'EXISTS_USER_PERMISSION',
} as const;
