export const HOLIDAY_ACTIONS = {
  CREATE: 'CREATE_HOLIDAY',
  UPDATE: 'UPDATE_HOLIDAY',
  ARCHIVE: 'ARCHIVE_HOLIDAY',
  RESTORE: 'RESTORE_HOLIDAY',
  PAGINATED_LIST: 'PAGINATED_LIST_HOLIDAY',
  BY_DATE: 'BY_DATE_HOLIDAY',
  COMBOBOX: 'COMBOBOX_HOLIDAY',
} as const;
