export const USER_ACTIONS = {
  CREATE: 'CREATE_USER',
  UPDATE: 'UPDATE_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD_USER',
  VERIFY_EMAIL: 'VERIFY_EMAIL_USER',
  ARCHIVE: 'ARCHIVE_USER',
  RESTORE: 'RESTORE_USER',
  PAGINATED_LIST: 'PAGINATED_LIST_USER',
  BY_USERNAME: 'BY_USERNAME_USER',
  BY_EMAIL: 'BY_EMAIL_USER',
  COMBOBOX: 'COMBOBOX_USER',
  LOGIN: 'LOGIN_USER',
} as const;
